services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_LASTFM_ENABLED: "true"
      ND_LASTFM_APIKEY: "11661dbad2c8969d971b0b503e49ac9e"
      ND_LASTFM_SECRET: "1ba521e1f2e1092bd601b3f5e92a3ca3"
    volumes:
      - "./data:/data:z"
      - "/home/dominik/Music:/music/anduril:ro,z"
      - "/run/media/dominik/ainulindale:/music/ainulindale:ro,z"

