# SUBTITLES
stretch-image-subs-to-screen=yes

# FONTS
osd-font='Adwaita Sans'
sub-font='Helvetica Bold'
sub-color='#FFFFFF'
sub-border-size=2.5
sub-border-color='#000000'
sub-shadow-offset=1.2
sub-shadow-color='#66000000'
sub-bold=yes
sub-blur=0.3

# HARDWARE DECODING
hwdec=auto

